### ISSUE TITLE
USER STORY: Search personal Records

### ISSUE THREAD

**Issue by SophieTiger** [SophieTiger/chalk-talk-api#34]
As a **User ** I can **search my personal records ** so that **I can find one specific based on search criteria**

Acceptance Criteria:
A search field is present on personal records page 
Search field allows keywords to be entered and is searching for the personal record Exercise

Tasks:
- [ ] Implement search functionality for personal records based on filters
- [ ] Test that search functionality is working as expected

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the PersonalRecordList view to ensure the search functionality is working correctly for the 'exercise' field. Added a comment to clarify the usage of the search feature.

You can review changes in this commit: https://github.com/mnmnk43434/SophieTiger-chalk-talk-api-34/commit/7e6332c3084da6b43565df84daf724ad7c0753fa.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by SophieTiger** [comment]
Taken out of scope due to lack of time
